# Generated by Django 5.2.5 on 2025-09-01 13:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('text', 'Text'), ('scale', 'Scale')], max_length=20)),
                ('scale_min_label', models.CharField(blank=True, max_length=100, null=True)),
                ('scale_max_label', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='survey.question')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2, null=True)),
                ('reason', models.CharField(choices=[('bachelor', 'Bachelor'), ('masters', 'Master’s'), ('phd', 'PhD'), ('research', 'Research Paper'), ('market', 'Market Research')], max_length=20, null=True)),
                ('duration_days', models.IntegerField()),
                ('min_duration_minutes', models.PositiveIntegerField(default=1)),
                ('max_duration_minutes', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('choice_set', models.TextField(help_text='Enter choices separated by commas, e.g., ممتاز,ممتاز جداً,عادي')),
                ('required_submissions', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_surveys', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.university')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey'),
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('income_min', models.PositiveIntegerField(blank=True, null=True)),
                ('income_max', models.PositiveIntegerField(blank=True, null=True)),
                ('countries', models.ManyToManyField(blank=True, to='accounts.country')),
                ('fields_of_study', models.ManyToManyField(blank=True, to='accounts.fieldofstudy')),
                ('professions', models.ManyToManyField(blank=True, to='accounts.profession')),
                ('universities', models.ManyToManyField(blank=True, to='accounts.university')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographic', to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.question')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SolvedSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_surveys', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solved_entries', to='survey.survey')),
            ],
            options={
                'unique_together': {('survey', 'freelancer')},
            },
        ),
    ]
