# Generated by Django 5.2.1 on 2025-06-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_solvedsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='required_submissions',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
