# Generated by Django 5.2.1 on 2025-06-04 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_verified'),
        ('survey', '0003_survey_required_submissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='num_questions',
        ),
        migrations.AddField(
            model_name='survey',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'Arabic')], default='en', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='max_duration_minutes',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='survey',
            name='min_duration_minutes',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='survey',
            name='reason',
            field=models.CharField(choices=[('bachelor', 'Bachelor'), ('masters', 'Master’s'), ('phd', 'PhD'), ('research', 'Research Paper'), ('market', 'Market Research')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.university'),
        ),
    ]
