# Generated by Django 5.2.1 on 2025-06-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_remove_survey_num_questions_survey_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='max_duration_minutes',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='survey',
            name='min_duration_minutes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
