# Generated by Django 5.2.1 on 2025-06-09 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_alter_question_question_type_alter_question_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solvedsurvey',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
