# Generated by Django 5.2.1 on 2025-06-13 21:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_question_scale_max_label_question_scale_min_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solvedsurvey',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
