# Generated by Django 5.2.1 on 2025-06-14 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_verified'),
        ('survey', '0009_alter_solvedsurvey_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('income_min', models.PositiveIntegerField(blank=True, null=True)),
                ('income_max', models.PositiveIntegerField(blank=True, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country')),
                ('field_of_study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.fieldofstudy')),
                ('profession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profession')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographic', to='survey.survey')),
                ('university', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.university')),
            ],
        ),
    ]
