# Generated by Django 5.2.1 on 2025-06-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_is_verified'),
        ('survey', '0010_demographic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographic',
            name='country',
        ),
        migrations.RemoveField(
            model_name='demographic',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='demographic',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='demographic',
            name='university',
        ),
        migrations.AddField(
            model_name='demographic',
            name='countries',
            field=models.ManyToManyField(blank=True, to='accounts.country'),
        ),
        migrations.AddField(
            model_name='demographic',
            name='fields_of_study',
            field=models.ManyToManyField(blank=True, to='accounts.fieldofstudy'),
        ),
        migrations.AddField(
            model_name='demographic',
            name='professions',
            field=models.ManyToManyField(blank=True, to='accounts.profession'),
        ),
        migrations.AddField(
            model_name='demographic',
            name='universities',
            field=models.ManyToManyField(blank=True, to='accounts.university'),
        ),
    ]
