# Generated by Django 5.2.1 on 2025-06-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_remove_demographic_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solvedsurvey',
            name='status',
        ),
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.CharField(choices=[('publish', 'Published'), ('unpublish', 'UnPublished')], default='unpublish', max_length=10),
        ),
    ]
