# Generated by Django 5.2.1 on 2025-06-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_remove_solvedsurvey_status_survey_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='status',
        ),
        migrations.AddField(
            model_name='survey',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
